# Port of HTTP(S) proxy server on the local end
port: 7890

# Port of SOCKS5 proxy server on the local end
socks-port: 7891

# Transparent proxy server port for Linux and macOS (Redirect TCP and TProxy UDP)
# redir-port: 7892

# Transparent proxy server port for Linux (TProxy TCP and TProxy UDP)
# tproxy-port: 7893

# HTTP(S) and SOCKS4(A)/SOCKS5 server on the same port
# mixed-port: 7890

# authentication of local SOCKS5/HTTP(S) server
# authentication:
#  - "user1:pass1"
#  - "user2:pass2"

# Set to true to allow connections to the local-end server from
# other LAN IP addresses
allow-lan: true

# This is only applicable when `allow-lan` is `true`
# '*': bind all IP addresses
# 192.168.122.11: bind a single IPv4 address
# "[aaaa::a8aa:ff:fe09:57d8]": bind a single IPv6 address
bind-address: '*'

# Clash router working mode
# rule: rule-based packet routing
# global: all packets will be forwarded to a single endpoint
# direct: directly forward the packets to the Internet
mode: rule

# Clash by default prints logs to STDOUT
# info / warning / error / debug / silent
log-level: info

# When set to false, resolver won't translate hostnames to IPv6 addresses
ipv6: false

# RESTful web API listening address
external-controller: 127.0.0.1:9090

# A relative path to the configuration directory or an absolute path to a
# directory in which you put some static web resource. Clash core will then
# serve it at `http://{{external-controller}}/ui`.
external-ui: folder

# Secret for the RESTful API (optional)
# Authenticate by spedifying HTTP header `Authorization: Bearer ${secret}`
# ALWAYS set a secret if RESTful API is listening on 0.0.0.0
# secret: ""

# Outbound interface name
interface-name: en0

# fwmark on Linux only
routing-mark: 6666

# Static hosts for DNS server and connection establishment (like /etc/hosts)
#
# Wildcard hostnames are supported (e.g. *.clash.dev, *.foo.*.example.com)
# Non-wildcard domain names have a higher priority than wildcard domain names
# e.g. foo.example.com > *.example.com > .example.com
# P.S. +.foo.com equals to .foo.com and foo.com
hosts:
  # '*.clash.dev': 127.0.0.1
  # '.dev': 127.0.0.1
  # 'alpha.clash.dev': '::1'

profile:
  # Store the `select` results in $HOME/.config/clash/.cache
  # set false If you don't want this behavior
  # when two different configurations have groups with the same name, the selected values are shared
  store-selected: false

  # persistence fakeip
  store-fake-ip: true

# DNS server settings
# This section is optional. When not present, the DNS server will be disabled.
dns:
  enable: false
  listen: 0.0.0.0:53
  # ipv6: false # when the false, response to AAAA questions will be empty

  # These nameservers are used to resolve the DNS nameserver hostnames below.
  # Specify IP addresses only
  default-nameserver:
    - 114.114.114.114
    - 8.8.8.8
  enhanced-mode: fake-ip # or redir-host (not recommended)
  fake-ip-range: 198.18.0.1/16 # Fake IP addresses pool CIDR
  # use-hosts: true # lookup hosts and return IP record
  
  # Hostnames in this list will not be resolved with fake IPs
  # i.e. questions to these domain names will always be answered with their
  # real IP addresses
  # fake-ip-filter:
  #   - '*.lan'
  #   - localhost.ptlogin2.qq.com
  
  # Supports UDP, TCP, DoT, DoH. You can specify the port to connect to.
  # All DNS questions are sent directly to the nameserver, without proxies
  # involved. Clash answers the DNS question with the first result gathered.
  nameserver:
    - 114.114.114.114 # default value
    - 8.8.8.8 # default value
    - tls://dns.rubyfish.cn:853 # DNS over TLS
    - https://1.1.1.1/dns-query # DNS over HTTPS
    - dhcp://en0 # dns from dhcp
    # - '8.8.8.8#en0'

  # When `fallback` is present, the DNS server will send concurrent requests
  # to the servers in this section along with servers in `nameservers`.
  # The answers from fallback servers are used when the GEOIP country
  # is not `CN`.
  # fallback:
   #  - tcp://1.1.1.1
    # - 'tcp://1.1.1.1#en0'

  # If IP addresses resolved with servers in `nameservers` are in the specified
  # subnets below, they are considered invalid and results from `fallback`
  # servers are used instead.
  #
  # IP address resolved with servers in `nameserver` is used when
  # `fallback-filter.geoip` is true and when GEOIP of the IP address is `CN`.
  #
  # If `fallback-filter.geoip` is false, results from `nameserver` nameservers
  # are always used if not match `fallback-filter.ipcidr`.
  #
  # This is a countermeasure against DNS pollution attacks.
   #fallback-filter:
    # geoip: true
     #-code: CN
     #ipcidr:
     #  - 240.0.0.0/4
#     domain:
 #      - '+.google.com'
 #      - '+.facebook.com'
#       - '+.youtube.com'
  
  # Lookup domains via specific nameservers
  # nameserver-policy:
  #   'www.baidu.com': '114.114.114.114'
  #   '+.internal.crop.com': '10.0.0.1'

proxy-providers:
  provider1:
    type: http
    url: "https://raw.githubusercontent.com/Strange69/Clash/main/provider1.yaml"    
    interval: 1600
    path: ./provider1.yaml
    health-check:
      enable: true
      interval: 600
      # lazy: true
      url: http://www.gstatic.com/generate_204
#  test:
#    type: file
#    path: /test.yaml
#    health-check:
#      enable: true
#      interval: 36000
#      url: http://www.gstatic.com/generate_204

proxy-groups:
  - name: ðŸ”°Proxy
    type: select
    use:
     - provider1
rules:
  - DOMAIN-SUFFIX,google.com,ðŸ”°Proxy
  - DOMAIN-SUFFIX,google,ðŸ”°Proxy
  - DOMAIN-KEYWORD,google,ðŸ”°Proxy
  - DOMAIN,google.com,ðŸ”°Proxy
  - DOMAIN-SUFFIX,fb.com,ðŸ”°Proxy
  - DOMAIN-SUFFIX,fb.me,ðŸ”°Proxy
  - DOMAIN-SUFFIX,fbaddins.com,ðŸ”°Proxy
  - DOMAIN-SUFFIX,fbcdn.net,ðŸ”°Proxy
  - DOMAIN-SUFFIX,fbsbx.com,ðŸ”°Proxy
  - DOMAIN-SUFFIX,fbworkmail.com,ðŸ”°Proxy
  - DOMAIN-SUFFIX,instagram.com,ðŸ”°Proxy
  - DOMAIN-SUFFIX,m.me,ðŸ”°Proxy
  - DOMAIN-SUFFIX,messenger.com,ðŸ”°Proxy
  - DOMAIN-SUFFIX,oculus.com,ðŸ”°Proxy
  - DOMAIN-SUFFIX,oculuscdn.com,ðŸ”°Proxy
  - DOMAIN-SUFFIX,rocksdb.org,ðŸ”°Proxy
  - DOMAIN-SUFFIX,whatsapp.com,ðŸ”°Proxy
  - DOMAIN-SUFFIX,whatsapp.net,ðŸ”°Proxy
  - DOMAIN-KEYWORD,facebook,ðŸ”°Proxy
  - DOMAIN-KEYWORD,twitter,ðŸ”°Proxy
  - DOMAIN-SUFFIX,t.me,ðŸ”°Proxy
  - DOMAIN-SUFFIX,tdesktop.com,ðŸ”°Proxy
  - DOMAIN-SUFFIX,telegra.ph,ðŸ”°Proxy
  - DOMAIN-SUFFIX,telegram.me,ðŸ”°Proxy
  - DOMAIN-SUFFIX,telegram.org,ðŸ”°Proxy
  - DOMAIN-SUFFIX,local,DIRECT
  - IP-CIDR,192.168.0.0/16,DIRECT,no-resolve
  - IP-CIDR,10.0.0.0/8,DIRECT,no-resolve
  - IP-CIDR,172.16.0.0/12,DIRECT,no-resolve
  - IP-CIDR,127.0.0.0/8,DIRECT,no-resolve
  - IP-CIDR,100.64.0.0/10,DIRECT,no-resolve
  - IP-CIDR,125.209.208.0/20,ðŸ”°Proxy,no-resolve
  - IP-CIDR,147.92.128.0/17,ðŸ”°Proxy,no-resolve
  - IP-CIDR,203.104.144.0/21,ðŸ”°Proxy,no-resolve
  - DOMAIN-SUFFIX,ad.com,REJECT
  - SRC-IP-CIDR,192.168.1.201/32,DIRECT
  # optional param "no-resolve" for IP rules (GEOIP, IP-CIDR, IP-CIDR6)
  - IP-CIDR,127.0.0.0/8,DIRECT
  - GEOIP,MM,DIRECT
  - DST-PORT,80,DIRECT
  - SRC-PORT,7777,DIRECT
  - MATCH,ðŸ”°Proxy
