
port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
mode: rule
log-level: silent
allow-lan: true
external-controller: 0.0.0.0:9090
bind-address: "*"
ipv6: false
dns:
  enable: true
  ipv6: false
  enhanced-mode: redir-host
  listen: 0.0.0.0:7894
  fallback-filter:
    geoip: false
    ipcidr:
    - 240.0.0.0/4
  nameserver:
    - https://puredns.org/dns-query
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
    - tls://puredns.org:853
    - tls://1.1.1.1:853
    - tls://8.8.8.8:853
  fallback:
    - tcp://108.137.44.39
    - tcp://108.137.44.9
    - tcp://1.1.1.1
    - tcp://8.8.8.8
    - 1.1.1.1
    - 8.8.8.8
    - 2001:4860:4860::8888
    - 2406:da19:66f:e810:2f1b:9ce8:a5f1:132f
tun:
  enable: true
  stack: system 
  macOS-auto-route: true
  macOS-auto-detect-interface: true
  dns-hijack:
    - tcp://108.137.44.39:53
experimental:
  interface-name: en0
  
  

ipv6: false
proxy-providers:
  strangeproxy:
    type: http
    url: "https://raw.githubusercontent.com/Strange69/Private/main/Proxy/strangeproxy.yaml"
    interval: 3600
    path: ./strangeproxy.yaml
    health-check:
      enable: true
      interval: 600
      #lazy: true
      url: http://www.gstatic.com/generate_204
      
proxy-groups:
- name: ðŸ”°Proxy
  type: select
  use:
  - strangeproxy
  
rule-providers:
  
  Browser:
    type: http
    url: "https://raw.githubusercontent.com/Strange69/Private/main/Rule/browser.yaml"
    behavior: classical
    path: ./browser.yaml
    
  Facebook:
    type: http
    url: "https://raw.githubusercontent.com/Strange69/Private/main/Rule/facebook.yaml"
    behavior: classical
    path: ./facebook.yaml
  
  Block:
    type: http
    url: "https://raw.githubusercontent.com/Strange69/Private/main/Rule/block.yaml"
    behavior: classical
    path: ./block.yaml
    
  LAN:
    type: http
    url: "https://raw.githubusercontent.com/Strange69/Private/main/Rule/lan.yaml"
    behavior: classical
    path: ./lan.yaml
  
  Google:
    type: http
    url: "https://raw.githubusercontent.com/Strange69/Private/main/Rule/google.yaml"
    behavior: classical
    path: ./google.yaml
    
  Tiktok:
    type: http
    url: "https://raw.githubusercontent.com/Strange69/Private/main/Rule/tiktok.yaml"
    behavior: classical
    path: ./tiktok.yaml
  
  Youtube:
    type: http
    url: "https://raw.githubusercontent.com/Strange69/Private/main/Rule/youtube.yaml"
    behavior: classical
    path: ./youtube.yaml
    
  
script:
  code: |
    def main(ctx, metadata):
        ruleset_action = {"Browser": "ðŸ”°Proxy",
            "Facebook": "DIRECT",
            "Block": "REJECT",
            "LAN": "DIRECT",
            "Google": "ðŸ”°Proxy",
            "Tiktok": "ðŸ”°Proxy",
            "Youtube": "ðŸ”°Proxy",
          }

        port = int(metadata["dst_port"])

        if metadata["network"] == "UDP":
            if port == "443,3478,4244,5222,5223,5228,5288,5242,5349,17000,20030,20031,34784,45395,50318,59234":
                ctx.log('[Script] matched QUIC traffic use browser')
                return "ðŸ”°Proxy"

        if metadata["dst_ip"] == "":
            metadata["dst_ip"] = ctx.resolve_ip(metadata["host"])

        port_list = [21, 22, 23, 53, 80, 123, 143, 194, 443, 465, 587, 853, 993, 995, 998, 2052, 2053, 2082, 2083, 2086, 2095, 2096, 5222, 5223, 5228, 5229, 5230, 5242, 8080, 8443, 8880, 8888, 8889, 17000, 20030, 20031, 20443, 49152, 50318, 50473, 50458, 50460, 50457, 50432, 50455, 50471, 50473, 50456, 59234]
        if port not in port_list:
            ctx.log('[Script] not common port use direct')
            return "DIRECT"

        if metadata["dst_ip"] == "":
            return "DIRECT"

        for ruleset in ruleset_action:
            if ctx.rule_providers[ruleset].match(metadata):
                return ruleset_action[ruleset]

        code = ctx.geoip(metadata["dst_ip"])
        if code == "CN":
            ctx.log('[Script] Geoip CN')
            return "DIRECT"

        ctx.log('[Script] FINAL')
        return "ðŸ”°Proxy"
rules:
- RULE-SET,Browser,ðŸ”°Proxy
- RULE-SET,Facebook,ðŸ”°Proxy
- RULE-SET,Block,REJECT
- RULE-SET,LAN,DIRECT
- RULE-SET,Google,ðŸ”°Proxy
- RULE-SET,Tiktok,ðŸ”°Proxy
- RULE-SET,Youtube,ðŸ”°Proxy
- IP-CIDR,198.18.0.1/16,REJECT,no-resolve
- GEOIP,CN,DIRECT
- MATCH,ðŸ”°Proxy
tun:
  enable: true
  stack: gvisor
  dns-hijack:
  - tcp://8.8.8.8:53
  - tcp://8.8.4.4:53
profile:
  store-selected: true
experimental:
  interface-name: en0
secret: Imstrange
bind-address: "*"
